//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionProduct
    {
        public int artikul { get; set; }
        public string Name { get; set; }
        public string Provide { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductUnit { get; set; }
        public System.DateTime DateAction { get; set; }
        public string StatusProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
