//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ActionProduct = new HashSet<ActionProduct>();
        }
    
        public int Artikul { get; set; }
        public string NameProduct { get; set; }
        public string Provider { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int quantity { get; set; }
        public string UnitProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionProduct> ActionProduct { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
